packages: []
catalogMode: prefer

catalogs:
  backend:
    better-sqlite3: ^12.5.0
  build:
    "@nuxt/content": ^3.10.0
    "@nuxt/image": ^2.0.0
  dev:
    "@nuxt/eslint": ^1.12.1
    eslint: ^9.39.2
    pnpm: ^10.27.0
    typescript: ~5.9.3
  frontend:
    "@vueuse/core": ^14.1.0
    "@vueuse/nuxt": ^14.1.0
    "@tailwindcss/vite": ^4.1.18
    tailwindcss: ^4.1.18
    nuxt: ^4.2.2

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
